#!/usr/bin/env python3
"""Upgrade project theory.md files to deep-dive guides.

Theory is decoupled from the validated setup/validate scripts, so rewriting it
is safe. Keyed by folder path under content/projects/. Run repeatedly as more
tracks are filled in. Each entry follows a consistent deep-dive structure:
concept → how it works → key syntax/commands → pitfalls → real-world.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROOT = ROOT / "content" / "projects"

THEORY: dict[str, str] = {}


def add(path: str, body: str):
    THEORY[path] = body.strip() + "\n"


# ─────────────────────────── LINUX & BASH ───────────────────────────
add("linux/01-sysinfo-dashboard", """
# Deep Dive: System Information Dashboards

## Why this matters
Before any monitoring stack exists, the first tool an engineer reaches for is a
shell script that answers "what is this box doing right now?". Understanding
*where the kernel exposes state* is what separates copy-paste admins from people
who can debug a server with nothing but Bash.

## Where the data actually lives
Linux exposes almost everything through **virtual filesystems** — files that
aren't on disk but are generated by the kernel on read:

| Source | Holds |
|--------|-------|
| `/proc/cpuinfo` | per-core CPU model, flags |
| `/proc/loadavg` | 1/5/15-min load averages + running procs |
| `/proc/meminfo` | every memory counter the kernel tracks |
| `/proc/uptime` | seconds since boot |
| `/sys/class/...` | devices, thermal zones, network counters |

Tools like `free`, `uptime`, `nproc`, and `df` are mostly *formatters* over
these files. Reading the raw file (`cat /proc/loadavg`) and parsing it yourself
is often more portable than depending on a tool's output columns.

## Techniques you'll practise
- **Command substitution** `cores=$(nproc)` to capture output into variables.
- **`awk` field extraction** to pull one column out of `free`/`df` — e.g.
  `free -m | awk '/Mem:/ {print $2}'`.
- **`printf`** for aligned, predictable output (never trust `echo` for
  formatting across shells).
- A **`--help`/usage guard** so the script behaves like a real CLI tool.

## Common pitfalls
- Parsing `df` without `-P` (POSIX) — long device names wrap onto two lines and
  break your `awk` column math. Always use `df -P`.
- Assuming `free` exists — on minimal/busybox systems it may not; reading
  `/proc/meminfo` is the robust fallback.
- Locale-dependent number formats; force `LC_ALL=C` for stable parsing.

## Real-world
This is the seed of every "node health" check, the body of a Nagios/Prometheus
textfile-collector script, and the first thing you SSH in and run during an
incident.
""")

add("linux/02-backup-rotation", """
# Deep Dive: Backups, Rotation & Retention

## The three jobs of a real backup script
1. **Capture** a consistent snapshot (here: a timestamped `tar.gz`).
2. **Rotate** — bound disk usage by keeping only the newest *N* archives.
3. **Log** — leave an audit trail so you can prove *when* a backup ran and
   whether it succeeded.

A backup you can't restore, or one that silently fills the disk and stops, is
worse than no backup because it creates false confidence.

## Timestamps that sort
Name archives `backup-$(date +%Y%m%d-%H%M%S).tar.gz`. The `YYYYMMDD-HHMMSS`
layout is **lexicographically sortable**, so `ls -1t` (by mtime) and a plain
alphabetical sort agree — which is what makes rotation reliable.

## The rotation one-liner, explained
```bash
ls -1t "$DEST"/backup-*.tar.gz | tail -n +$((KEEP+1)) | xargs -r rm -f
```
- `ls -1t` lists newest-first.
- `tail -n +$((KEEP+1))` skips the first `KEEP` (the keepers) and emits the rest.
- `xargs -r rm -f` deletes them; `-r` avoids running `rm` on empty input.

## Safety & idempotence
- `mkdir -p "$DEST"` so the first run can't fail on a missing directory.
- Fail loudly if the **source** is missing — never log "success" for an empty
  backup.
- `set -euo pipefail` so a failed `tar` aborts instead of rotating away good
  archives.

## Common pitfalls
- Backing up a live database with `tar` — you get a torn, inconsistent copy. Use
  the DB's dump tool (`pg_dump`, `mysqldump`) or snapshot the filesystem.
- Rotation counting *files in the dir* instead of *matching the glob* — stray
  files skew the count.

## Real-world
This pattern underlies `logrotate`, cron-driven DB dumps, and the retention
policies behind tools like restic, Velero, and cloud snapshot lifecycles.
""")

add("linux/03-log-analyzer", """
# Deep Dive: Log Analysis with the Unix Toolkit

## The pipeline mindset
Log analysis is the canonical demonstration of the Unix philosophy: chain
small, single-purpose filters with `|` and let each do one transform. You can
answer surprisingly deep questions about traffic, errors, and abuse with
`grep`, `awk`, `sort`, `uniq`, and `wc` — no database required.

## The building blocks
- **`awk '{print $N}'`** — split each line on whitespace and emit field *N*
  (the client IP is usually `$1` in access logs).
- **`sort | uniq -c`** — `uniq` only collapses *adjacent* duplicates, so you
  **must** `sort` first; `-c` prefixes each group with its count.
- **`sort -rn`** — sort those counts numerically, descending.
- **`head -n N`** — take the top N.

The famous "top talkers" recipe:
```bash
awk '{print $1}' access.log | sort | uniq -c | sort -rn | head -3
```

## Filtering for signal
- `grep -c ERROR` counts error lines without printing them.
- `awk '$9 ~ /^5/'` matches 5xx status codes by field, far more precise than a
  blind `grep 500` that also matches byte counts or URLs.

## Common pitfalls
- Forgetting to `sort` before `uniq -c` — you'll get fragmented, wrong counts.
- Whitespace vs. delimiter assumptions — combined log format quotes the request,
  so `$7` is the path only because the quotes are counted as fields. Know your
  log format.
- Huge files: prefer streaming (`awk`/`grep`) over loading into memory.

## Real-world
Every SRE triages incidents this way first. The same shapes become Loki/LogQL
queries, Elasticsearch aggregations, and Splunk searches — the tool changes, the
thinking doesn't.
""")

add("linux/04-user-manager", """
# Deep Dive: User Management & Idempotent State

## Modelling state in a file
Real user management touches `/etc/passwd`, `useradd`, and PAM — privileged,
hard to test. This project teaches the *logic* against a simple
`user:fullname` database file, which is exactly how you'd prototype before
wiring in real system calls.

## Idempotence is the whole game
An operation is **idempotent** if running it twice has the same effect as
running it once. `add alice` must not create a duplicate the second time:
```bash
grep -q "^$user:" "$DB" || echo "$user:$full" >> "$DB"
```
The `grep -q … ||` guard is the canonical idempotent-append pattern. This single
idea is the foundation of configuration management (Ansible, Puppet) — every
"resource" is just an idempotent assertion about desired state.

## Argument dispatch with `case`
A subcommand CLI (`add`/`del`/`list`/`count`) is a `case "$1" in … esac`
dispatcher. Validate arity (`$#`) and print a usage line on the `*)` default.

## Editing in place
`sed -i "/^$user:/d" "$DB"` deletes a matching line. Anchoring with `^` and the
`:` delimiter prevents `alice` from also matching `alice2`.

## Common pitfalls
- Unanchored patterns deleting/ matching the wrong rows.
- Word-splitting on names with spaces — quote every expansion (`"$full"`).
- Race conditions if two runs edit the file at once (real tooling locks).

## Real-world
This is the mental model behind `useradd`/`userdel` wrappers, bulk onboarding
scripts, and the idempotent `user:` module in Ansible.
""")

add("linux/05-disk-alert", """
# Deep Dive: Threshold Alerting

## Anatomy of an alert
Every alert has the same skeleton: **measure → compare to a threshold → act
(notify) → record**. Get this right in Bash and you understand the core loop
that Prometheus Alertmanager, Nagios, and CloudWatch all formalize.

## Measuring disk usage cleanly
```bash
usage=$(df -P / | awk 'NR==2 {gsub("%","",$5); print $5}')
```
- `df -P` forces POSIX single-line output (no wrapping on long device names).
- `NR==2` skips the header row.
- `gsub("%","",$5)` strips the percent sign so `$5` is a plain integer you can
  compare with `-gt`.

## Comparison & exit semantics
`[ "$usage" -gt "$threshold" ]` does an integer test. Decide what the script's
**exit code** means — a non-zero exit when over threshold lets cron or a CI step
treat the alert as a failure.

## Why log every run
Alerting that only speaks up on failure hides *whether it ran at all*. Appending
`date usage threshold` every run gives you a heartbeat — silence then means the
checker itself died, which is its own alert.

## Common pitfalls
- Comparing the raw `45%` string numerically — the `%` makes it non-numeric.
- Off-by-one on `>` vs `>=` at the boundary.
- Hard-coding the mount point; parameterise it.

## Real-world
This is a textfile-collector script for `node_exporter`, a classic cron
disk-space guard, and the conceptual ancestor of a Prometheus
`predict_linear()` "disk will fill in 4h" alert.
""")

add("linux/06-service-watcher", """
# Deep Dive: Health Checks & Self-Healing

## Liveness, then remediation
A watchdog does two things: **detect** that a service is unhealthy, and
**remediate** (restart it). Modelling the service as a marker file keeps the
focus on the control loop rather than on process plumbing — but the logic maps
directly onto checking a PID, a port, or an HTTP endpoint.

## The control loop
```
observe current state  ->  compare to desired (up)  ->  if drifted, act  ->  log
```
This **observe/diff/act** loop is the same reconciliation pattern Kubernetes
controllers run continuously. Your script is a one-shot reconciler; cron makes
it periodic.

## Detecting real services
Swap the marker check for any of:
- `pgrep -x nginx` — is the process running?
- `nc -z localhost 80` — is the port accepting connections?
- `curl -fsS localhost/health` — does the app say it's healthy?

The last is best: a process can be *running* but *wedged*. Liveness should test
behaviour, not mere existence.

## Logging events, not spam
Log a `restart` only on transitions, `ok` otherwise, so the log reads like an
incident timeline rather than noise.

## Common pitfalls
- Restart loops: if the service crashes instantly, a naive watcher hot-loops.
  Real supervisors add backoff and a crash-count ceiling.
- Treating "process exists" as "healthy".

## Real-world
This is `systemd` `Restart=on-failure`, Docker `--restart`, and Kubernetes
liveness probes, distilled to its essence.
""")

add("linux/07-file-organizer", """
# Deep Dive: Globbing & Parameter Expansion

## The problem
A directory full of mixed files is the perfect playground for two Bash
superpowers: **globbing** (matching filenames) and **parameter expansion**
(string surgery without calling external tools).

## Extracting an extension
```bash
ext="${f##*.}"     # strip the longest leading match up to the last dot
```
- `${var##pattern}` removes the **longest** prefix matching `pattern`.
- `${var#pattern}` removes the **shortest**.
- `${var%pattern}` / `${var%%pattern}` do the same from the **end**.

Knowing these four saves you from spawning `basename`, `dirname`, `cut`, or
`sed` in a loop — faster and with no quoting surprises.

## Looping over files safely
```bash
for f in *; do [ -f "$f" ] || continue; ...; done
```
- The `[ -f "$f" ]` guard skips directories (including the ones you're creating).
- Always quote `"$f"` — filenames can contain spaces, and unquoted expansion
  re-splits them.
- Handle the no-extension case (`"$ext" = "$f"` means no dot was found).

## Common pitfalls
- Re-picking moved files: if you `mv` files into a subdir of the same directory
  you're iterating, re-globbing can re-pick them. Snapshot the list or guard by
  type.
- Files beginning with `.` are skipped by default globs (`shopt -s dotglob`).
- Spaces/newlines in names — quoting and `-f` checks handle the common cases.

## Real-world
The same expansions power log-shipping scripts, media organizers, build
artifact sorters, and the rename logic in dotfiles managers.
""")

add("linux/08-cron-report", """
# Deep Dive: Scheduling with cron

## Two halves of a scheduled job
A scheduled task is a **payload** (the script that does the work) plus a
**schedule** (when cron runs it). Keeping them separate — a clean `genreport.sh`
and a one-line crontab entry — makes the payload testable on its own.

## Reading a crontab line
```
0 6 * * *  /root/genreport.sh
│ │ │ │ │
│ │ │ │ └── day of week (0-6, Sun=0)
│ │ │ └──── month (1-12)
│ │ └────── day of month (1-31)
│ └──────── hour (0-23)
└────────── minute (0-59)
```
`0 6 * * *` = 06:00 every day. `*/15 * * * *` = every 15 minutes. `@daily`,
`@reboot` are shorthands.

## Why cron scripts break in production
cron runs with a **minimal environment**: a short `PATH`, no `~/.bashrc`, often
`/bin/sh` not Bash, and `HOME` possibly unset. Scripts that work in your
interactive shell fail under cron because of this. Defenses:
- Use **absolute paths** for binaries and files.
- Set `PATH` explicitly at the top of the script.
- Redirect output (`>> log 2>&1`) — cron emails stdout by default, which often
  silently black-holes.

## Common pitfalls
- Relative paths (cron's CWD is `$HOME`, not where the script lives).
- Assuming Bash features under `/bin/sh`.
- Forgetting that `%` is special in crontab lines (must be escaped).

## Real-world
Cron still drives backups, certificate renewals, report generation, and cleanup
jobs everywhere; Kubernetes `CronJob` borrows the exact schedule syntax.
""")

add("linux/09-admin-menu", """
# Deep Dive: Interactive TUIs in Bash

## When a menu is the right interface
For runbooks and guided ops tools, a menu-driven script is friendlier than a
pile of flags — operators pick an action instead of memorizing syntax. The
pattern is a `while` loop around a `read` and a `case` dispatch.

## The loop
```bash
while true; do
  print_menu
  read -r choice || break      # `|| break` handles EOF (Ctrl-D / piped input)
  case "$choice" in
    1) action_one ;;
    q|Q) break ;;
    *) echo "unknown choice" ;;
  esac
done
```

## Reading input robustly
- `read -r` — the `-r` stops backslashes being interpreted; almost always what
  you want.
- The `|| break` on `read` is crucial: when input is **piped** (or the user
  hits Ctrl-D), `read` returns non-zero at EOF. Without the guard you get an
  infinite loop. This is also what makes the tool **scriptable/testable**:
  `printf '1\\nq\\n' | ./admin.sh`.

## Separating presentation from logic
Keep each action in its own function. The menu just routes; functions do the
work. This is the same MVC instinct that scales to real apps.

## Common pitfalls
- No EOF handling → infinite loop when piped.
- Unquoted `$choice` in tests.
- Doing heavy work inline so the tool can't be unit-tested.

## Real-world
Installer TUIs, `raspi-config`, interactive deployment helpers, and "break-glass"
operator consoles all use this shape.
""")

add("linux/10-bootstrapper", """
# Deep Dive: Project Scaffolding & Bootstrapping

## What "bootstrapping" means
Turning a bare machine (or empty directory) into a known-good starting state:
the right directory layout, baseline files, and declared dependencies. Doing
this *as code* makes environments reproducible — the same idea that grows into
Terraform, cloud-init, and `create-react-app`.

## Driving from a manifest
Reading the package list from `packages.txt` instead of hard-coding it is the
key move: **data-driven** scripts separate *what* (the manifest) from *how* (the
script). Add a package by editing data, not logic.
```bash
while IFS= read -r pkg; do
  [ -n "$pkg" ] && install "$pkg"
done < packages.txt
```
- `IFS=` preserves leading/trailing whitespace in each line.
- `read -r` keeps backslashes literal.
- The `[ -n "$pkg" ]` guard skips blank lines.

## Idempotent scaffolding
`mkdir -p` creates the tree without erroring if it already exists, so the
bootstrapper is safe to re-run — a property every provisioning tool needs.

## Common pitfalls
- Word-splitting the manifest if you `for pkg in $(cat …)` (breaks on spaces and
  is slower). Prefer the `while read` loop.
- Not validating the target name (`${1:?usage}` gives a clean error).
- Overwriting an existing project without warning.

## Real-world
This is the essence of `cloud-init`, Dockerfile `RUN` setup blocks, dotfiles
installers, and scaffolding CLIs.
""")


def main():
    written = 0
    for rel, body in THEORY.items():
        target = PROOT / rel / "theory.md"
        if not target.parent.exists():
            print(f"  !! missing project dir: {rel}")
            continue
        target.write_text(body, encoding="utf-8")
        written += 1
    print(f"Enriched {written} theory.md files")


if __name__ == "__main__":
    main()
